#!/bin/sh

LOCKER=""
LAUNCHER="rofi -no-custom -width 24 -hide-scrollbar -dmenu -i -p System:"
OPTIONS=" Shutdown\n Reboot\n Hibernate\n Suspend\n Logout\n Lock"
option=`echo "${OPTIONS}" | $LAUNCHER`

lock() {
   i3lock -n -i ~/lock-wallpaper.png
}

case $option in
    *Lock*)
        lock
        ;;
    *Logout*)
        i3-msg exit
        ;;
    *Suspend*)
        lock && systemctl suspend
        ;;
    *Hibernate*)
        lock && systemctl hibernate
        ;;
    *Reboot*)
        systemctl reboot
        ;;
    *Shutdown*)
        systemctl poweroff
        ;;
    *)
        ;;
esac

exit 0
